package com.mycompany.foodorderingdesktopapp.screens;


import Interfaces.Values;
import com.mycompany.foodorderingdesktopapp.database_connectivity.ConnectionClass;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.UserModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class LoginScreen extends javax.swing.JFrame implements Values{
    
    UserModel loginUser;
    
    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginTitleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        usernameTF = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 450));
        getContentPane().setLayout(null);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTitleLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        loginTitleLabel.setText("Login");
        loginPanel.add(loginTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 60, -1));

        usernameLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        usernameLabel.setText("Username");
        loginPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 146, 80, -1));

        passwordLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        passwordLabel.setText("Password");
        loginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 245, 80, -1));

        loginButton.setBackground(new java.awt.Color(255, 255, 0));
        loginButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 318, 97, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jButton2.setText("SignIn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        loginPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 318, 100, -1));
        loginPanel.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 271, 30));
        loginPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 238, 271, 32));

        exitButton.setBackground(new java.awt.Color(255, 255, 0));
        exitButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        loginPanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 100, -1));

        getContentPane().add(loginPanel);
        loginPanel.setBounds(0, 0, 800, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        final String username = usernameTF.getText();
        final String password = passwordField.getText();
        if (username.isEmpty()|| password.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Username or password is empty");
        } else if (username.isEmpty() && password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter username and password");
        } else {
            final String statement = "SELECT * from users where username=? and password=?";
            PreparedStatement preparedStatement;
            try {
                preparedStatement = ConnectionClass.getInstance().connection.prepareStatement(statement);
                preparedStatement.setString(1, username);
                preparedStatement.setString(2, password);

                ResultSet resultSet = preparedStatement.executeQuery();

                while (resultSet.next()) {
                    System.out.println("in result set next while");
                    UserModel userModel = new UserModel();
                    userModel.setId(Integer.parseInt(resultSet.getString("id")));
                    userModel.setUsername(resultSet.getString("username"));
                    userModel.setPassword(resultSet.getString("password"));
                    userModel.setRole(resultSet.getInt("role"));
                    System.out.println("in result set next role " + userModel.getRole());
                    loginUser=userModel;
                    
                    switch (userModel.getRole()) {
                       
                        case 1:
                            JOptionPane.showMessageDialog(null, "user found");
                            dispose();
                             new  HomeScreenForAdmin(loginUser).setVisible(true);
                            break;
                        case 2:
                            JOptionPane.showMessageDialog(null, "user found");
                            dispose();
                            new HomeScreenForManager(loginUser).setVisible(true);
                            break;
                        default:
                            break;
                    }
                    return;
                }
                JOptionPane.showMessageDialog(null, "Invalid username or password");
            } catch (SQLException ex) {
                Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new SignInScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginTitleLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
