package com.mycompany.foodorderingdesktopapp.screens;

import Interfaces.Values;
import com.mycompany.foodorderingdesktopapp.database_connectivity.ConnectionClass;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author acer
 */
public class SignInScreen extends javax.swing.JFrame implements Values {

    
    /**
     * Creates new form SignInScreen
     */
    public SignInScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        singupPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        signupButton = new javax.swing.JButton();
        signUpLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButtom = new javax.swing.JButton();
        blurPanel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 450));
        setMinimumSize(new java.awt.Dimension(800, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(0, 0, 0));
        backgroundPanel.setForeground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setMaximumSize(new java.awt.Dimension(800, 450));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        singupPanel.setBackground(new java.awt.Color(153, 0, 0));
        singupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username");
        singupPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, -1));

        passwordLabel.setBackground(new java.awt.Color(255, 255, 0));
        passwordLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        singupPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, -1));

        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });
        singupPanel.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 190, -1));

        signupButton.setBackground(new java.awt.Color(204, 102, 0));
        signupButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        signupButton.setText("Sign-up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        singupPanel.add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, -1));

        signUpLabel.setBackground(new java.awt.Color(255, 255, 255));
        signUpLabel.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(255, 255, 255));
        signUpLabel.setText("Sign Up for Admin");
        singupPanel.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, -1));

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        singupPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 190, -1));

        loginButtom.setBackground(new java.awt.Color(204, 102, 0));
        loginButtom.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        loginButtom.setText("Back to Login");
        loginButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtomActionPerformed(evt);
            }
        });
        singupPanel.add(loginButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 141, -1));

        backgroundPanel.add(singupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 380, 300));

        blurPanel.setBackground(new java.awt.Color(0, 0, 0 , 80));
        blurPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                blurPanelComponentAdded(evt);
            }
        });
        blurPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLabel.setBackground(new java.awt.Color(153, 0, 0));
        iconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\FoodOrderingDesktopApp\\FoodOrderingDesktopApp\\src\\main\\java\\com\\mycompany\\foodorderingdesktopapp\\images\\foodapp82.jpg")); // NOI18N
        iconLabel.setText("jLabel1");
        iconLabel.setMaximumSize(new java.awt.Dimension(800, 450));
        iconLabel.setMinimumSize(new java.awt.Dimension(800, 450));
        iconLabel.setPreferredSize(new java.awt.Dimension(800, 450));
        blurPanel.add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        backgroundPanel.add(blurPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtomActionPerformed
        // TODO add your handling code here:
       LoginScreen login = new LoginScreen();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginButtomActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        // TODO add your handling code here:
        
      String username = usernameTF.getText();
        String password = passwordField.getText();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter username");
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter password");
        } else {
            final String searchStatement = "SELECT * from users where username=?";
            
            try {
                PreparedStatement searchPreparedStatement = ConnectionClass.getInstance().connection.prepareStatement(searchStatement);
                searchPreparedStatement.setString(1, username);
                
                ResultSet searhResultSet = searchPreparedStatement.executeQuery();
                
                while (searhResultSet.next()) {
                    JOptionPane.showMessageDialog(null, "Email already exists");
                    return;
                }
                
                final String insertStatement = "INSERT INTO users(username, password,role) values(?,?,?)";
                PreparedStatement preparedStatement = ConnectionClass.getInstance().connection.prepareStatement(insertStatement);
                preparedStatement.setString(1, username);
                preparedStatement.setString(2,  password);
                preparedStatement.setInt(3,  ADMIN_ROLE);

                final int isAdded = preparedStatement.executeUpdate();

                if (isAdded > 0) {
                    JOptionPane.showMessageDialog(null, "User Added.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error, Please Try Again!");
                }
            } catch (SQLException ex) {
                System.out.println("error in " + SignInScreen.class.getName() + " = " + ex);
            }
        }
        
    }//GEN-LAST:event_signupButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
       
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed

       
       
    }//GEN-LAST:event_usernameTFActionPerformed

    private void blurPanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_blurPanelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_blurPanelComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new SignInScreen().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel blurPanel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton loginButtom;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JButton signupButton;
    private javax.swing.JPanel singupPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
