/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.foodorderingdesktopapp.screens;

/**
 *
 * @author acer
 */
public class SplasScreen extends javax.swing.JFrame {
    static SplasScreen splash = new SplasScreen();
    /**
     * Creates new form SplasScreen
     */
    public SplasScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashPanel = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        progressPercentageLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        splashPanel.setBackground(new java.awt.Color(255, 255, 255));
        splashPanel.setMinimumSize(new java.awt.Dimension(800, 450));
        splashPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBar.setBackground(new java.awt.Color(204, 204, 204));
        progressBar.setForeground(new java.awt.Color(153, 0, 51));
        splashPanel.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 706, 20));
        splashPanel.add(progressPercentageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 114, 29));

        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\FoodOrderingDesktopApp\\FoodOrderingDesktopApp\\src\\main\\java\\com\\mycompany\\foodorderingdesktopapp\\images\\logo4.png")); // NOI18N
        splashPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 710, 260));

        getContentPane().add(splashPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplasScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplasScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplasScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplasScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                splash.setVisible(true);
                
            }
        }); 
        
          try {
             
            for(int counter = 0; counter<=100; counter++){
                Thread.sleep(50);
                splash.progressBar.setValue(counter);
                splash.progressPercentageLabel.setText(Integer.toString(counter) + "%");
                
            }
        } 
        catch (InterruptedException e) {
            System.out.println("Error in Splash Screen = " + e);
        }
          

        LoginScreen loginScreen = new LoginScreen();
        //splash.setVisible(false);
        loginScreen.setVisible(true);
        splash.dispose();     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logoLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressPercentageLabel;
    private javax.swing.JPanel splashPanel;
    // End of variables declaration//GEN-END:variables
}
